# Generated by Django 2.2.1 on 2019-05-15 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brandname', models.CharField(max_length=30, verbose_name='品牌名字')),
                ('pub_data', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
            ],
        ),
        migrations.CreateModel(
            name='subbrand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subbrandname', models.CharField(max_length=30, verbose_name='子品牌')),
                ('color', models.CharField(choices=[(1, '绿色'), (2, '蓝色'), (3, '黄色')], max_length=10, verbose_name='颜色')),
                ('memory', models.CharField(choices=[(2, '2GB'), (4, '4GB'), (8, '8GB'), (16, '16GB')], max_length=10, verbose_name='内存')),
                ('wj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mall.brand', verbose_name='父品牌')),
            ],
        ),
    ]
