# Generated by Django 2.2.1 on 2019-05-15 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subbrand',
            name='color',
            field=models.CharField(choices=[('1', '绿色'), ('2', '蓝色'), ('3', '黄色')], max_length=10, verbose_name='颜色'),
        ),
        migrations.AlterField(
            model_name='subbrand',
            name='memory',
            field=models.CharField(choices=[('2', '2GB'), ('4', '4GB'), ('8', '8GB'), ('16', '16GB')], max_length=10, verbose_name='内存'),
        ),
    ]
