# Generated by Django 0002.0002.0001 on 2019-05-15 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booktest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='pub_date',
            field=models.DateTimeField(verbose_name='出版时间'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=30, verbose_name='书籍名称'),
        ),
        migrations.AlterField(
            model_name='hero',
            name='gender',
            field=models.CharField(choices=[(1, '男'), (2, '女')], max_length=10, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='hero',
            name='name',
            field=models.CharField(max_length=30, verbose_name='英雄名字'),
        ),
        migrations.AlterField(
            model_name='hero',
            name='skill',
            field=models.CharField(max_length=30, null=True, verbose_name='技能'),
        ),
        migrations.AlterField(
            model_name='hero',
            name='wj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booktest.book', verbose_name='书'),
        ),
    ]
