# Generated by Django 0002.0002.0001 on 2019-05-15 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booktest', '0002_auto_20190515_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='gender',
            field=models.CharField(choices=[('0001', '男'), ('0002', '女')], max_length=10, verbose_name='性别'),
        ),
    ]
