# Generated by Django 0002.0002.0001 on 2019-05-17 08:29

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('booktest', '0003_auto_20190515_1116'),
    ]

    operations = [
        migrations.CreateModel(
            name='testmanage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
            ],
            managers=[
                ('manage', django.db.models.manager.Manager()),
            ],
        ),
    ]
